### PR TITLE
fix: allow .j2 suffix for templates, strip off for file/service names

### PR DESCRIPTION
**Pull request by richm**
Cause: The code was assuming all templated files had a .j2 suffix.  The
role would fail if given a template without a .j2 suffix.

Consequence: The documentation did not clearly state this.

Fix: The code has been changed to so that templated files do not have to
have a .j2 suffix.

Result: The role works with any templated file suffix.

Signed-off-by: Rich Megginson <rmeggins@redhat.com>

### CODE REVIEW

**Comment by richm** [comment]
fixes https://github.com/linux-system-roles/systemd/issues/11

**Comment by richm** [comment]
[citest]

**Comment by richm** [comment]
[citest]

**Review by msekletar — COMMENTED** [review]
LGTM

**Review by spetrosi — APPROVED** [review]

**Pull request merged**
